version: "3"
services:
  app:
    container_name: full_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    restart: on-failure
    volumes:
      - .:/usr/src/app
    depends_on:
      - forum-postgres
    networks:
      - forum

  forum-postgres:
    image: postgres:latest
    container_name: forum-postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - forum

volumes:
  api:
  database_postgres:

networks:
  forum:
    driver: bridge
